insert into customer (id, name) values (1001, 'Aurora Cinema');
insert into customer (id, name) values (1002, 'Blue Horizon Theater');
insert into customer (id, name) values (1003, 'Midnight Playhouse');
insert into customer (id, name) values (1004, 'Golden Age Cinema');
insert into customer (id, name) values (1005, 'Velvet Curtain Theatre');
insert into customer (id, name) values (1006, 'Silver Star Playhouse');
insert into customer (id, name) values (1007, 'Oceanic Opera House');
insert into customer (id, name) values (1008, 'Grand Heritage Cinema');
insert into customer (id, name) values (1009, 'Royal Majestic Theater');
insert into customer (id, name) values (1010, 'Eclipse Stage');
insert into customer (id, name) values (1011, 'Nebula Arts Center');
insert into customer (id, name) values (1012, 'Stardust Cinema');
insert into customer (id, name) values (1013, 'Vintage Vine Theatre');
insert into customer (id, name) values (1014, 'Phoenix Playhouse');
insert into customer (id, name) values (1015, 'Cosmos Cinema');
insert into customer (id, name) values (1016, 'Infinity Opera');
insert into customer (id, name) values (1017, 'Marble Arch Theater');
insert into customer (id, name) values (1018, 'Paramount Palace');
insert into customer (id, name) values (1019, 'Neon Night Cinema');
insert into customer (id, name) values (1020, 'Summit Stage');
insert into customer (id, name) values (1021, 'Liberty Lantern Theatre');
insert into customer (id, name) values (1022, 'Wild Rose Playhouse');
insert into customer (id, name) values (1023, 'Atlas Arts Cinema');
insert into customer (id, name) values (1024, 'Zenith Theater');
insert into customer (id, name) values (1025, 'Titanium Cinema');