-- Limpieza total previa (el orden Jenga)

INSERT INTO play (id, code, name, type) VALUES 
(1, 'h', 'Hamlet', 'Tragedia'),
(2, 'esdlb', 'El sabueso de los Baskerville', 'Drama'),
(3, 'f', 'Fahrenheit 451', 'Futuristica'),
(4, 'rj', 'Romeo y Julieta', 'Tragedia'),
(5, 'mo', 'Macbeth', 'Tragedia'),
(6, 'eo', 'Edipo Rey', 'Tragedia'),
(7, 'la', 'La Antigona', 'Tragedia'),
(8, 'ecdls', 'El caballero de la selva', 'Drama'),
(9, 'cc', 'Crónicas Marcianas', 'Futuristica'),
(10, 'uval', 'Un mundo feliz', 'Futuristica'),
(11, '1984', '1984', 'Futuristica'),
(12, 'odf', 'Odisea del Futuro', 'Futuristica'),
(13, 'le', 'La Eneida', 'Tragedia'),
(14, 'ddc', 'Divina Comedia', 'Drama'),
(15, 'lp', 'La Promesa', 'Drama'),
(16, 'ceelhu', 'Crimen en el hotel universal', 'Drama'),
(17, 'nr', 'Neuromante', 'Futuristica'),
(18, 'be', 'Blade Runner', 'Futuristica'),
(19, 'el', 'El Lear', 'Tragedia'),
(20, 'o', 'Otelo', 'Tragedia'),
(21, 'p', 'Prometeo', 'Tragedia'),
(22, 'fm', 'Fausto', 'Drama'),
(23, 'lc', 'La Celestina', 'Drama'),
(24, 'vds', 'Viaje de sombras', 'Drama'),
(25, 'da', 'Duna Arrakis', 'Futuristica'),
(26, 'se', 'Solaris Estacion', 'Futuristica'),
(27, 'm', 'Metropolis', 'Futuristica'),
(28, 'rc', 'Robots de Ciudad', 'Futuristica'),
(29, 'ia', 'Inteligencia Artificial', 'Futuristica'),
(30, 'te', 'Troyanas Eneida', 'Tragedia'),
(31, 'm1', 'Medea', 'Tragedia'),
(32, 'ec', 'Esperando a Godot', 'Drama'),
(33, 'lcdb', 'La casa de Bernarda', 'Drama'),
(34, 'ba', 'Bodas de Sangre', 'Drama'),
(35, 'yo', 'Yerma Obra', 'Drama'),
(36, 'f1', 'Fundacion', 'Futuristica'),
(37, 'em', 'El Mesias', 'Futuristica'),
(38, 'cl', 'Ciber Leyendas', 'Futuristica'),
(39, 'ae', 'Almas Espectros', 'Tragedia'),
(40, 'dr', 'Don Ricardo', 'Drama');