version: '3.8'

services:

  database_v_angular_21: 
    image: postgres:alpine
    container_name: database_v_angular_21
    restart: always
    ports:
      - "5433:5432" # En tu PC usás el 5433
    volumes:
      - postgres_v_angular_21:/var/lib/postgresql 
    environment:
      POSTGRES_USER: APP
      POSTGRES_PASSWORD: APP
      POSTGRES_DB: labprog

  backend_v_angular_21:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_v_angular_21
    volumes:
      - ./backend:/app
      - ../common/backend/m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - "8081:8080" # API en http://localhost:8081
      - "35730:35729"
      - "5006:5005"
    depends_on:
      - database_v_angular_21

  frontend_v_angular_21:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_v_angular_21
    working_dir: /home/node/cli
    command: ng serve --host=0.0.0.0
    restart: always
    ports:
      - "4201:4200" # Web en http://localhost:4201
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/home/node      
    depends_on: 
      - backend_v_angular_21

volumes:
  postgres_v_angular_21:
